Swift 3
delannoyk/KDEDateLabel pull request #2
Opened 2017-02-24 21:28 UTC by edc1591

This PR updates this repo to Swift 3.

2017-03-03 00:12 UTC, delannoyk requested changes
Hey! Thanks for updating this! Left some quick comments regarding minor access control issues.

2017-03-03 00:12 UTC, delannoyk commented on KDEDateLabel.swift
> +internal class KDEWeakReferencer<T: NSObject>: NSObject {
Could you use `fileprivate` here?

2017-03-03 00:12 UTC, delannoyk commented on KDEDateLabel.swift
> +internal class KDEDateLabelsHolder: NSObject {
Could you use `fileprivate` here?

2017-03-03 00:12 UTC, delannoyk commented on KDEDateLabel.swift
> +    var timer: Timer?
^^ I think these should remain `private`

2017-03-03 00:12 UTC, delannoyk commented on KDEDateLabel.swift
> +    internal func updateText() {
Could this remain `private` or `fileprivate`?

2017-03-05 20:38 UTC, edc1591 commented
@delannoyk Thanks for taking a look! Just push a commit with those changes.

2017-03-05 23:13 UTC, delannoyk commented
@edc1591 Cool, thanks for this!

2017-03-05 23:13 UTC, merged